Pull request for issue #2676 to include episode aired date in newsletter
tidusjar/Ombi pull request #3802
Opened 2020-10-08 12:29 UTC by AdamWorley

I have only implemented the aired date for newly added to plex as that's what was requested and I'm unfamiliar with emby.

2020-10-09 21:41 UTC, tidusjar requested changes
We are now also adding the `Aired` property onto each of the entities, there needs to be data migrations created for SQLite and MySQL for this. Then they should also be populated when they are created (Not just in the RecentlyAddedEngine, e.g. the PlexContentSync). 

So far you have done a good job! Just it's not totally finished.

The other option is instead of storing the AirDate against the actual entity, in the NewsLetterJob we actually look up the media on TheMovieDb/TvMaze which should also contain that information, so we could easily leverage that

2020-10-09 21:41 UTC, tidusjar commented on src/Ombi.Api.Plex/Models/Metadata.cs
> -        //public string originallyAvailableAt { get; set; }
Can we please undo this change?

2020-10-09 21:41 UTC, tidusjar commented on src/Ombi.Helpers/StringHelper.cs
> +        public static string BuildEpisodeList(IEnumerable<(int EpisodeNumber, DateTime? Aired)> orderedEpisodes)
Looks good, but don't feel like this belongs in the `StringHelper`? It's very specific to what's going on

2020-10-18 09:00 UTC, AdamWorley commented
I have made the changes you (@tidusjar) have recommended and I have leveraged the Movie db for the season/episode info.

I opted to use the tv/season endpoint, instead of the episode endpoint to avoid spamming api requests.

2020-12-25 09:16 UTC, closed without merging